import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..");
const distPath = path.join(repoRoot, "apps", "dispatcher", "dist", "modules", "server", "review-memory.js");
await import("./dispatcher-state.js");
const tsModule = await import(pathToFileURL(distPath).href);
export const createMemoryStore = tsModule.createMemoryStore;
export const extractLessonFromReview = tsModule.extractLessonFromReview;
export const extractLessonFromFailed = tsModule.extractLessonFromFailed;
export const extractLessonFromRework = tsModule.extractLessonFromRework;
export const shouldInjectLesson = tsModule.shouldInjectLesson;
export const filterLessonsForInjection = tsModule.filterLessonsForInjection;
export const loadMemoryStore = tsModule.loadMemoryStore;
export const injectLessonsIntoContext = tsModule.injectLessonsIntoContext;
