export {
  DEFAULT_ACTIVITY_SELECTORS,
  DEFAULT_COMPOSER_SELECTORS,
  DEFAULT_NEW_CHAT_SELECTORS,
  DEFAULT_POST_ACTION_DELAY_MS,
  DEFAULT_RESPONSE_IDLE_MS,
  DEFAULT_RESPONSE_POLL_INTERVAL_MS,
  DEFAULT_RESPONSE_SELECTORS,
  DEFAULT_RESPONSE_TIMEOUT_MS,
  DEFAULT_SEND_BUTTON_SELECTORS,
  buildCaptureExpression,
  buildDriverConfig,
  buildPrepareInputExpression,
  buildPrepareSessionExpression,
  buildReadinessExpression,
  buildSubmitExpression,
  buildTriggerSubmitExpression,
  createBrowserDomAdapter,
  createTraeAutomationDriver,
  extractAutomationResponse,
} from "@tingrudeng/automation-gateway-core";

export type {
  DriverConfig,
  DriverOptions,
  ExtractAutomationResponseOptions,
  ExtractAutomationResponseResult,
  SnapshotEntry,
  TraeAutomationDriver,
  TraeAutomationDriverOptions,
} from "@tingrudeng/automation-gateway-core";
